[package]
name = "rusting-raceway"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.16.1"
bevy_ggrs = "0.18"
bevy_matchbox = { version = "0.12", features = ["ggrs"] }
clap = { version = "4.5.48", features = ["cargo"] }
